project_id = "atmwbscgckxxremychoa"

[functions.google-calendar]
verify_jwt = false

[functions.finance-chat]
verify_jwt = false

[functions.finance-analysis]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.categorize-grocery]
verify_jwt = false
